# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/diepw50/CPRE-488-Labs/MP-1/docs/ZedBoard/zedboard_master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_interconnect_0_0/design_2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_interconnect_0_0 || ORIG_REF_NAME==design_2_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_100M_0/design_2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_ppm5_0_0/design_2_axi_ppm5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_ppm5_0_0 || ORIG_REF_NAME==design_2_axi_ppm5_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_system_ila_0_0 || ORIG_REF_NAME==design_2_system_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
